# Generated by Django 2.2 on 2019-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190423_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
